In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
# here, we can see that -

# brand, fuel, owner -> categorical column
# km_driven, selling_price -> numerical column
# And, we have to focus on categorical column 

df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [5]:
df['brand'].nunique()

32

In [6]:
# similarly,check for ech categorical column

df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [7]:
df['fuel'].nunique()

4

In [8]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [9]:
df['owner'].nunique()

5

In [10]:
''' initially, we don't consider "brand" column because 
     if we use it then data becomes very lengthy 
            '''

' initially, we don\'t consider "brand" column because \n     if we use it then data becomes very lengthy \n            '

# Implementing OneHotEncoding using Pandas

In [11]:
pd.get_dummies(df, columns=['fuel', 'owner'], dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

# (k-1) OHE uisng Pandas

In [12]:
pd.get_dummies(df, columns=['fuel', 'owner'], drop_first = True, dtype=int)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

In [13]:
# But, during ML projects, we don't use Panda's OHE method becuase pandas gives different result at different result

# OHE using sklearn

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
# we also do the same here train_test_split method:-

X_train, X_test, y_train, y_test = train_test_split( 
                                     df.drop('selling_price', axis=1), 
                                     df['selling_price'], 
                                     test_size=0.2, 
                                     random_state=0  )

In [16]:
X_train

           brand  km_driven    fuel         owner
3042     Hyundai      60000     LPG   First Owner
1520        Tata     150000  Diesel   Third Owner
2611     Hyundai     110000  Diesel  Second Owner
3544    Mahindra      28000  Diesel  Second Owner
4138      Maruti      15000  Petrol   First Owner
...          ...        ...     ...           ...
4931        Tata      70000  Diesel   Third Owner
3264        Ford     100000  Diesel  Second Owner
1653     Hyundai      90000  Petrol  Second Owner
2607  Volkswagen      90000  Diesel   First Owner
2732     Hyundai     110000  Petrol   First Owner

[6502 rows x 4 columns]

In [17]:
X_test

         brand  km_driven    fuel         owner
3558   Hyundai      40000  Diesel   First Owner
233   Mahindra      70000  Diesel   First Owner
7952    Maruti       5000  Petrol   First Owner
572     Maruti     120000  Petrol   Third Owner
6960     Lexus      20000  Petrol   First Owner
...        ...        ...     ...           ...
7576      Fiat     100000  Diesel   Third Owner
1484    Maruti     120000  Petrol   Third Owner
1881    Maruti      40000  Diesel   First Owner
4917   Hyundai       2350  Petrol   First Owner
5934   Hyundai      80000  Diesel  Second Owner

[1626 rows x 4 columns]

In [18]:
# now import OneHotEncoder class 

from sklearn.preprocessing import OneHotEncoder

In [19]:
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

'''
  here, drop='first' -> it removes the first two columns from 'fuel' and 'owner' 
  and, sparse_output=False -> by using there is no need to use .toarray() for converting into numpy arrays
  and, dtype=np.int32 -> it is used to convert float values into integer values
'''

X_train_new = ohe.fit_transform(X_train[['fuel','owner']])
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [20]:
X_train_new

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [21]:
X_test_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0]])

In [22]:
# now, we have to remov that 2 columns('brand','km_driven') from X_train and append that 2 columns with X_train_new

X_train[['brand','km_driven']].values

array([['Hyundai', 60000],
       ['Tata', 150000],
       ['Hyundai', 110000],
       ...,
       ['Hyundai', 90000],
       ['Volkswagen', 90000],
       ['Hyundai', 110000]], dtype=object)

In [23]:
''' now, we can see both X_train_new and X_train are numpy arrays then, we have to add them 
        horizonatally in the stack  '''

np.hstack((X_train[['brand','km_driven']].values, X_train_new))

array([['Hyundai', 60000, 0, ..., 0, 0, 0],
       ['Tata', 150000, 1, ..., 0, 0, 1],
       ['Hyundai', 110000, 1, ..., 1, 0, 0],
       ...,
       ['Hyundai', 90000, 0, ..., 1, 0, 0],
       ['Volkswagen', 90000, 1, ..., 0, 0, 0],
       ['Hyundai', 110000, 0, ..., 0, 0, 0]], dtype=object)

In [24]:

np.hstack((X_train[['brand','km_driven']].values, X_train_new)).shape

(6502, 9)

In [25]:
''' 
   now, we are going include "brand" column also into the dataset 
      '''

' \n   now, we are going include "brand" column also into the dataset \n      '

# OHE with Top categories

In [26]:
counts = df['brand'].value_counts()

In [27]:
df['brand'].nunique()
threshold=100

In [28]:
# make a variable "repl" and store the value which is less than threshold

repl = counts[counts <= threshold].index   # "index" prints the names of brand which has value > threshold

In [29]:
# it gives an output in true/false for columns

pd.get_dummies(df['brand'].replace(repl, 'uncommom'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommom
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False

In [30]:
# for getting o/p respone in 0/1, we have to add "dtype=int" above

pd.get_dummies(df['brand'].replace(repl, 'uncommon'), dtype=int)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,0,0,0,0,1,0,0,0,0,0,0,0,0
8124,0,0,0,0,1,0,0,0,0,0,0,0,0
8125,0,0,0,0,0,0,1,0,0,0,0,0,0
8126,0,0,0,0,0,0,0,0,0,1,0,0,0
8127,0,0,0,0,0,0,0,0,0,1,0,0,0